branches:
  thrustmin: double
  aplanarity: double
  sphericity: double
  foxwolfram20: double
  thrustmaj: double
  eec_c2_1: double
  pt: double
  phi: double
  split12: double
  tauwta2tauwta1: double
  eec_d2_1: double
  yfilt: double
  mu12: double
  tauwta2: double
  angularity: double
  zcut12: double
  eta: double
  tauwta1: double
  planarflow: double
  label: int
  m: double
  weight: double

#    eec_c2_2: double
#  eec_d2_2: double
#  tau1: double
#    tau21: double
#      tau2: double